# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "kdc" do |node|
	  node.vm.box = "ubuntu/xenial64"
	  node.vm.provider "virtualbox" do |vb|
	     # Display the VirtualBox GUI when booting the machine
	     # vb.gui = true
	  
	     # Customize the amount of memory on the VM:
	     vb.memory = "1024"
	  end
	  node.vm.hostname = "kdc"
	  node.disksize.size = "10GB"
      node.vm.synced_folder "Shared", "/vagrant_shared"
	  node.vm.network "public_network"
	  node.vm.network "private_network", ip: "192.168.128.176"
	  node.vm.provision :shell, inline: <<-SHELL
	   sudo su
	   cd /root
	   sudo apt-get update
	   sudo apt-get upgrade -y
	   sudo apt-get install -y openssh-client openssh-server wget bzip2 default-jdk curl zlibc ntp

	   cp /vagrant_shared/hosts /etc/hosts
	   ulimit -n 10000
	   echo 1 > /proc/sys/vm/swappiness
	   printf "\nvm.swappiness=1\n" >> /etc/sysctl.conf

	   service ntp start
	  SHELL
	end
end