# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "kdc" do |node|
    node.vm.box = "centos/7"
    node.vm.provider "virtualbox" do |vb|
       # Display the VirtualBox GUI when booting the machine
       # vb.gui = true
    
       # Customize the amount of memory on the VM:
       vb.memory = "1024"
    end
    node.vm.hostname = "kdc"
    node.disksize.size = "50GB"
    node.vm.synced_folder "Shared", "/vagrant_shared"
    node.vm.network "public_network"
    node.vm.network "private_network", ip: "10.0.0.50", virtualbox__intnet: true
    node.vm.provision :shell, env: { "buildNumber" => "2.6.5.0" }, inline: <<-SHELL
     sudo su
     cd /root
     
     yum install -y wget net-tools
    SHELL
  end
end