# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "ipaserver" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
        end
        hostname = "ipaserver.test.hadoop.com"
        node.vm.hostname = "#{hostname}"
        node.disksize.size = "50GB"
        node.vm.synced_folder "Shared", "/vagrant_shared"
        node.vm.synced_folder "../common", "/vagrant_common"
        node.vm.network "public_network"
        ipaddress = "10.0.0.60"
        node.vm.network "private_network", ip: "#{ipaddress}", virtualbox__intnet: true
        node.vm.provision :shell, inline: <<-SHELL
            sudo su
            cd /root

            yum -y install https://centos7.iuscommunity.org/ius-release.rpm
            yum -y install epel-release python36u python36u-dev python36u-devel npm wget net-tools krb5-libs krb5-workstation git krb5-devel java-1.8.0-openjdk nginx
            yum -y install python36u-pip ansible pki-symkey pki-server

            mkdir .ssh
            ssh-keygen -t rsa -P "" -f .ssh/id_dsa
            cat .ssh/id_dsa.pub >> .ssh/authorized_keys
            chmod 700 .ssh
            chmod 600 .ssh/authorized_keys

            ipaddress=#{ipaddress}
            hostname=#{hostname}
            echo "nameserver $ipaddress" >> /etc/resolv.conf
            sed -i "s/127.0.0.1[ \t]*$hostname/$ipaddress\t$hostname/g" /etc/hosts

            ssh-keyscan -H ipaserver.test.hadoop.com > .ssh/known_hosts
            ssh-keyscan -H ipaserver >> .ssh/known_hosts

            git clone https://github.com/freeipa/ansible-freeipa.git --branch v0.1.8

            \\cp ansible-freeipa/playbooks/install-server.yml .
            \\cp /vagrant_shared/hosts hosts

            mkdir -p .ansible/plugins
            ln -s /root/ansible-freeipa/roles .ansible/roles
            ln -s /root/ansible-freeipa/plugins/modules .ansible/plugins/modules
            ln -s /root/ansible-freeipa/plugins/module_utils .ansible/plugins/module_utils

            ansible-playbook -v -i hosts install-server.yml
        SHELL
    end
end