# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "freeIPA" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
        end
        node.vm.hostname = "freeipa.test.hadoop.com"
        node.disksize.size = "50GB"
        node.vm.synced_folder "Shared", "/vagrant_shared"
        node.vm.synced_folder "../common", "/vagrant_common"
        node.vm.network "public_network"
        ipaddress = "10.0.0.60"
        node.vm.network "private_network", ip: "#{ipaddress}", virtualbox__intnet: true
        node.vm.provision :shell, inline: <<-SHELL
        sudo su
        cd /root

        curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo

        yum update
        yum upgrade -y
        yum -y install npm wget net-tools patch sbt krb5-devel

        chmod +x /vagrant_*/*.sh

        ipaddress=#{ipaddress}
        hostname=$(hostname -f | tr '[:upper:]' '[:lower:]')
        echo "nameserver $ipaddress" >> /etc/resolv.conf
        sed -i "s/127.0.0.1[ \t]*$hostname/$ipaddress\t$hostname/g" /etc/hosts

        yum install -y ipa-server ipa-server-dns bind-dyndb-ldap
        
        yum install -y mod_wsgi

        systemctl start named
        systemctl enable named

        ipa-server-install -p directoryManagerAdmin -a kerberosAdmin --ip-address=$ipaddress -n test.hadoop.com -r TEST.HADOOP.COM --mkhomedir -U --hostname=$hostname

        SHELL
    end
end