# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    config.vm.define "linuxdev" do |node|
        node.vm.box = "centos/7"
        node.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
        node.vm.hostname = "linuxdev"
        node.disksize.size = "50GB"
        node.vm.synced_folder "Shared", "/vagrant_shared", type: "virtualbox"
        node.vm.synced_folder "../common", "/vagrant_common", type: "virtualbox"
        node.vm.network "public_network"
        node.vm.network "private_network", ip: "10.0.0.50", virtualbox__intnet: true
        node.vm.provision :shell, inline: <<-SHELL
        sudo su
        cd /root

        curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo

        yum -y install https://centos7.iuscommunity.org/ius-release.rpm
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum -y install epel-release python36u python36u-dev npm wget net-tools git docker-ce protobuf-compiler patch sbt
        yum -y install python36u-pip

        wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
        yum -y install apache-maven

        wget https://downloads.lightbend.com/scala/2.12.8/scala-2.12.8.rpm
        yum -y install scala-2.12.8.rpm

        printf '\nexport MAVEN_OPTS="-Xmx1G -XX:MaxPermSize=256m"\n' >> /etc/bashrc

        systemctl start docker

        chmod +x /vagrant_*/*.sh

        ln -s /bin/pip3.6 /bin/pip
        pip install --upgrade pip
        pip install shyaml

        gitName=$(cat /vagrant_common/config.yaml | shyaml get-value git.name)
        gitEmail=$(cat /vagrant_common/config.yaml | shyaml get-value git.email)

        /vagrant_common/setupAuthentication.sh

        git config --global user.name "$gitName"
        git config --global user.email "$gitEmail"
        SHELL
    end
end