# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.define "jupyterhub" do |node|
        node.vm.box = "centos/7"
        node.vm.provider "virtualbox" do |vb|
            # Display the VirtualBox GUI when booting the machine
            # vb.gui = true

            # Customize the amount of memory on the VM:
            vb.memory = "2048"
        end
		hostname = "jupyterhub.test.hadoop.com"
		ipaddress = "10.0.0.40"
        node.vm.hostname = "#{hostname}"
        node.disksize.size = "50GB"
        node.vm.synced_folder "Shared", "/vagrant_shared"
        node.vm.synced_folder "../common", "/vagrant_common"
        node.vm.network "public_network"
        node.vm.network "private_network", ip: "#{ipaddress}", virtualbox__intnet: true
        node.vm.provision :shell, reset: "true", inline: <<-SHELL
	        sudo su
	        cd /root

			yum update
			yum upgrade -y
			yum -y install npm wget net-tools patch sbt krb5-devel

			yum install -y ipa-client
			# Installing this ahead of time is necessary in order to avoid an error when installing IPA-Client.
			yum install -y mod_wsgi

			systemctl start named
			systemctl enable named

			ipaddress=#{ipaddress}
			hostname=#{hostname}
			echo "nameserver $ipaddress" >> /etc/resolv.conf
			\\cp -f /vagrant_common/hosts /etc/hosts

			ipa-client-install --force-join -p admin -w kerberosAdmin --ip-address=$ipaddress --server=freeipa.test.hadoop.com --domain=test.hadoop.com --realm=TEST.HADOOP.COM -U --mkhomedir --hostname=$hostname

			# Note that this is done after FreeIPA is installed. 
			# For whatever reason, installing these before FreeIPA causes it to not start properly.
	        yum -y install https://centos7.iuscommunity.org/ius-release.rpm
	        yum -y install epel-release python3-3.6.8-10.el7.x86_64  python3-devel-3.6.8-10.el7.x86_64 git java-1.8.0-openjdk nginx
			
			# Allows for connections to occur for Nginx internally.
	        setsebool -P httpd_can_network_connect 1

			yum install -y npm
			npm install -g configurable-http-proxy

			rm -f /etc/nginx/nginx.conf
			\\cp /vagrant_shared/nginx.conf /etc/nginx/nginx.conf
			systemctl restart nginx

			echo "PATH=/root/miniconda3/bin:$PATH" >> /etc/bashrc
			export PATH="/root/miniconda3/bin:$PATH"

			wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
			chmod +x Miniconda3-latest-Linux-x86_64.sh
			./Miniconda3-latest-Linux-x86_64.sh -b

			conda init bash
			
			. /root/.bashrc

	        sparkVersion=2.1.3

			conda create -y --prefix /opt/jupyterhub python=3.6.8
			conda activate /opt/jupyterhub

			pip install jupyterhub jupyterlab
			pip install jupyterhub-ldapauthenticator

			mkdir -p /opt/jupyterhub/etc/jupyterhub/
			\\cp /vagrant_shared/jupyterhub_config.py /opt/jupyterhub/etc/jupyterhub/
			\\cp /vagrant_shared/jupyterhub.service /etc/systemd/system/jupyterhub.service

			systemctl daemon-reload
			systemctl enable jupyterhub.service
			systemctl start jupyterhub.service

			mkdir -p /usr/local/bin/apache-spark
			echo "Downloading Spark $sparkVersion"
			wget -q https://archive.apache.org/dist/spark/spark-$sparkVersion/spark-$sparkVersion-bin-hadoop2.7.tgz
			echo "Extracting Spark Binaries"
			tar -xzvf spark-$sparkVersion-bin-hadoop2.7.tgz > /dev/null
			mv spark-$sparkVersion-bin-hadoop2.7/* /usr/local/bin/apache-spark

			pip install --upgrade toree
			jupyter toree install --spark_home=/usr/local/bin/apache-spark/ --interpreters=Scala,SQL

			pip install "pyspark==$sparkVersion"

			ipAddress=$(ifconfig | grep --only-matching "192\.168\.[0-9]*\.[0-9]*" | head -n 1)
			echo "Jupyter is now running at http://$ipAddress/"
			echo "Username: admin"
			echo "User password: kerberosAdmin"
			SHELL
    end
end