# -*- mode: ruby -*-
# vi: set ft=ruby :

numMasters=1
numData=2

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  (1..numData).each do |i|
    config.vm.define "dat#{i}" do |node|
      node.vm.box = "ubuntu/xenial64"
      node.vm.provider "virtualbox" do |vb|
         # Display the VirtualBox GUI when booting the machine
         # vb.gui = true
      
         # Customize the amount of memory on the VM:
         vb.memory = "4096"
      end
      node.vm.hostname = "dat#{i}"
      node.disksize.size = "50GB"
      node.vm.synced_folder "Shared", "/vagrant_shared"
      node.vm.network "public_network"
      node.vm.network "private_network", ip: "192.168.128.#{i + 128 + numMasters - 1}"
      node.vm.provision :shell, env: { "buildNumber" => "2.6.0.0" }, inline: <<-SHELL
       sudo su
       cd /root
       sudo apt-get update
       sudo apt-get upgrade -y
       sudo apt-get install -y openssh-client openssh-server wget bzip2 default-jdk postgresql curl zlibc ntp

       cp /vagrant_shared/hosts /etc/hosts
       ulimit -n 10000
       echo 1 > /proc/sys/vm/swappiness
       printf "\nvm.swappiness=1\n" >> /etc/sysctl.conf

       service ntp start
       ssh-keygen -t rsa -P "" -f ~/.ssh/id_dsa
       cp ~/.ssh/id_dsa.pub /vagrant_shared/dat#{i}.pub

       wget -O /etc/apt/sources.list.d/ambari.list http://public-repo-1.hortonworks.com/ambari/ubuntu16/2.x/updates/2.6.0.0/ambari.list
       apt-key adv --recv-keys --keyserver keyserver.ubuntu.com B9733A7A07513CAD
       apt-get update
       apt-get install -y ambari-agent
      SHELL
    end
  end

  config.vm.define "mst1" do |node|
    node.vm.box = "ubuntu/xenial64"
    node.vm.provider "virtualbox" do |vb|
       # Display the VirtualBox GUI when booting the machine
       # vb.gui = true
    
       # Customize the amount of memory on the VM:
       vb.memory = "8192"
    end
    node.vm.hostname = "mst1"
    node.disksize.size = "50GB"
    node.vm.synced_folder "Shared", "/vagrant_shared"
    node.vm.network "public_network"
    node.vm.network "private_network", ip: "192.168.128.128"
    node.vm.provision :shell, env: { "buildNumber" => "2.6.0.0" }, inline: <<-SHELL
     sudo su
     cd /root
     sudo apt-get update
     sudo apt-get upgrade -y
     sudo apt-get install -y openssh-client openssh-server wget bzip2 default-jdk postgresql curl zlibc ntp

     cp /vagrant_shared/hosts /etc/hosts
     ulimit -n 10000
     echo 1 > /proc/sys/vm/swappiness
     printf "\nvm.swappiness=1\n" >> /etc/sysctl.conf

     service ntp start
     ssh-keygen -t rsa -P "" -f ~/.ssh/id_dsa
     cp ~/.ssh/id_dsa.pub /vagrant_shared/mst1.pub
     
     wget -O /etc/apt/sources.list.d/ambari.list http://public-repo-1.hortonworks.com/ambari/ubuntu16/2.x/updates/2.6.0.0/ambari.list
     apt-key adv --recv-keys --keyserver keyserver.ubuntu.com B9733A7A07513CAD
     apt-get update
     apt-get install -y ambari-server
     ambari-server setup -s --version=2.6.0.0

     ambari-server start
     
     ifconfig
    SHELL
  end
end